name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - name: Lint Proto
        run: buf lint api/proto

      - name: Check Breaking Changes
        if: github.event_name == 'pull_request'
        run: buf breaking --against "https://github.com/${GITHUB_REPOSITORY}.git#branch=main" --path api/proto

      - name: Lint Go
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: healthapp_db_test
          POSTGRES_USER: healthapp_user
          POSTGRES_PASSWORD: verysecretpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          go install github.com/bufbuild/buf/cmd/buf@latest
          go install connectrpc.com/connect/cmd/protoc-gen-connect-go@latest
          go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
          go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest

      - name: Generate code
        run: make generate-all

      - name: Run migrations
        run: |
          migrate -database "postgres://healthapp_user:verysecretpassword@localhost:5432/healthapp_db_test?sslmode=disable" -path db/migrations up

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
        env:
          HEALTHAPP_DATABASE_URL: postgres://healthapp_user:verysecretpassword@localhost:5432/healthapp_db_test?sslmode=disable

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          fail_ci_if_error: false

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          go install github.com/bufbuild/buf/cmd/buf@latest
          go install connectrpc.com/connect/cmd/protoc-gen-connect-go@latest
          go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

      - name: Generate code
        run: make generate-all

      - name: Build
        run: make build
