name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Configure git for private modules
        run: git config --global url."https://${{ github.token }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Download Go Modules
        run: go mod download && go mod tidy

      - name: Install Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - name: Lint Proto
        run: buf lint api/proto

      - name: Check Breaking Changes
        if: github.event_name == 'pull_request'
        run: buf breaking api/proto --against "https://${{ github.token }}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git#branch=main"

      - name: Lint Go
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: healthapp_db_test
          POSTGRES_USER: healthapp_user
          POSTGRES_PASSWORD: verysecretpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: make setup-tools

      - name: Generate code
        run: make generate-all

      - name: Run migrations
        run: |
          migrate -database "postgres://healthapp_user:verysecretpassword@localhost:5432/healthapp_db_test?sslmode=disable" -path db/migrations up

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
        env:
          HEALTHAPP_DATABASE_URL: postgres://healthapp_user:verysecretpassword@localhost:5432/healthapp_db_test?sslmode=disable

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: make setup-tools

      - name: Generate code
        run: make generate-all

      - name: Build
        run: make build
